# Generated by Django 2.2.6 on 2019-12-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default='50'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('RESTOCKING', 'Item needs restocking in few days'), ('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item already purchased')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplieraddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='suppliercity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplierstate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplierzipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
