# Generated by Django 2.2.6 on 2019-12-12 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0005_auto_20191208_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='id',
        ),
        migrations.AlterField(
            model_name='billingorder',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billingorders', to='pis.PurchaseOrder'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item already purchased'), ('RESTOCKING', 'Item needs restocking in few days')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='orderId',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
